name: qantu_frontend
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.13.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Conexión WebSocket para streaming en tiempo real
  web_socket_channel: ^3.0.2

  # Grabación de voz desde el micrófono (v5.1.2 para máxima compatibilidad Web)
  record: ^5.1.2

  # Reproducción de audio (.wav) local/red
  audioplayers: ^6.0.0

  # Peticiones HTTP para enviar el audio a STT
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Assets (imágenes, iconos, etc.)
  assets:
    - assets/fonts/

  # Configuración de Fuentes Locales
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500

    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
